apiVersion: v1
kind: ResourceQuota
metadata:
  name: lago-linx-iap-test
  labels:
    app.kubernetes.io/instance: lago-linx-iap-test
    environment: test
spec:
  hard:
    pods: "30"
    requests.cpu: "4"
    requests.memory: 8Gi
    limits.cpu: "12"
    limits.memory: 20Gi
